version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    # Adicione qualquer outra configuração necessária para o serviço do backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Adicione qualquer outra configuração necessária para o serviço do frontend
