version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:@localhost:3306/mydb?schema=public
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase

volumes:
  db-data:
